### ISSUE TITLE
Just want to say hi

### ISSUE THREAD

**Issue by GrimPixel** [oyd11/awesome-lang#9]
Looks like you are eager to learn languages. If you would like, please pay a visit to https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Internet-resources-for-polyglots

**Comment by oyd11** [comment]
This repo is less about me, and more about curating resources, I'm not personally interested in most of these languages.
Could you be more specific about this link  ?  I saw it starts with a bunch of programs like "red shift" / f-lux clones... I don't see what this has to do with language learning, thanks!

**Comment by GrimPixel** [comment]
If that is what you can read from the page, good luck then.
